apiVersion: v1
kind: Service
metadata:
  name: backend-demo
  namespace: devdeploy-workloads
  labels:
    app.kubernetes.io/name: backend-demo
    app.kubernetes.io/managed-by: devdeploy-hub
    devdeploy.io/application: backend-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend-demo
    devdeploy.io/application: backend-demo
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
