apiVersion: v1
kind: ConfigMap
metadata:
  name: devdeploy-config
  namespace: devdeploy
  labels:
    app.kubernetes.io/name: devdeploy-hub
data:
  JWT_ALGORITHM: HS256
  FRONTEND_ORIGIN: http://devdeploy.local
  ENVIRONMENT: development
  VITE_API_BASE_URL: http://devdeploy.local/api/v1
