apiVersion: v1
kind: Service
metadata:
  name: devdeploy-frontend
  namespace: devdeploy
  labels:
    app.kubernetes.io/name: devdeploy-hub
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devdeploy-hub
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
