apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devdeploy-ingress
  namespace: devdeploy
  labels:
    app.kubernetes.io/name: devdeploy-hub
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: devdeploy.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: devdeploy-backend
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: devdeploy-backend
                port:
                  number: 8000
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: devdeploy-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devdeploy-frontend
                port:
                  number: 80
