apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devdeploy
  labels:
    app.kubernetes.io/name: devdeploy-hub
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devdeploy-hub
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
