apiVersion: v1
kind: Secret
metadata:
  name: devdeploy-secret
  namespace: devdeploy
  labels:
    app.kubernetes.io/name: devdeploy-hub
type: Opaque
stringData:
  POSTGRES_DB: devdeploy
  POSTGRES_USER: devdeploy
  POSTGRES_PASSWORD: devdeploy
  JWT_SECRET_KEY: change-me-in-production
