apiVersion: v1
kind: Service
metadata:
  name: podinfo-final-demo-1
  namespace: devdeploy-workloads
  labels:
    app.kubernetes.io/name: podinfo-final-demo-1
    app.kubernetes.io/managed-by: devdeploy-hub
    devdeploy.io/application: podinfo-final-demo-1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: podinfo-final-demo-1
    devdeploy.io/application: podinfo-final-demo-1
  ports:
    - name: http
      port: 9898
      targetPort: 9898
      protocol: TCP
