apiVersion: v1
kind: ConfigMap
metadata:
  name: devdeploy-backend-config
  namespace: devdeploy
data:
  ENVIRONMENT: development
  JWT_ALGORITHM: HS256
  FRONTEND_ORIGIN: http://localhost:8080
  KUBERNETES_IN_CLUSTER: "true"
  PROMETHEUS_BASE_URL: ""
  LOKI_BASE_URL: ""
  GRAFANA_BASE_URL: ""
  DEVDEPLOY_OBSERVABILITY_ACCESS_MODE: kubernetes_service_proxy
  DEVDEPLOY_OBSERVABILITY_MONITORING_NAMESPACE: monitoring
  DEVDEPLOY_OBSERVABILITY_PROMETHEUS_SERVICE_NAME: kube-prometheus-stack-prometheus
  DEVDEPLOY_OBSERVABILITY_PROMETHEUS_SERVICE_PORT: "9090"
  DEVDEPLOY_OBSERVABILITY_LOKI_SERVICE_NAME: loki-gateway
  DEVDEPLOY_OBSERVABILITY_LOKI_SERVICE_PORT: "80"
  DEVDEPLOY_OBSERVABILITY_GRAFANA_SERVICE_NAME: kube-prometheus-stack-grafana
  DEVDEPLOY_OBSERVABILITY_GRAFANA_SERVICE_PORT: "80"
  DEVDEPLOY_OBSERVABILITY_WORKLOAD_KUBECONFIG: /var/run/devdeploy/workload-observability/kubeconfig
  DEVDEPLOY_OBSERVABILITY_WORKLOAD_KUBECONFIG_CONTEXT: devdeploy-workload-observability
  OBSERVABILITY_HEALTH_CACHE_SECONDS: "10"
  OBSERVABILITY_MAX_RESPONSE_BYTES: "2097152"
  GITOPS_ENABLED: "false"
  GITHUB_OWNER: Kaan-YASSIBAS
  GITHUB_REPO: devdeploy-hub
  GITOPS_WORKFLOW_FILE: gitops-workload-request.yml
  GITOPS_DELETE_WORKFLOW_FILE: gitops-workload-delete.yml
  GITOPS_TARGET_REF: main
  DEVDEPLOY_ARGOCD_ROOT_APPLICATION_NAME: devdeploy-workloads-root
  DEVDEPLOY_ARGOCD_NAMESPACE: argocd
  DEVDEPLOY_WORKLOAD_NAMESPACE: devdeploy-apps
  DEVDEPLOY_WORKLOAD_KUBECONFIG: ""
  DEVDEPLOY_WORKLOAD_KUBECONFIG_CONTEXT: ""
  DEVDEPLOY_STATUS_READER_MODE: kubernetes
