apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/api-status-smoke-nginx
  - apps/nginx-demo
  - apps/try-nginx
  - apps/try2-nginx
  - apps/try3-nginx
  - apps/ui-status-smoke-nginx
