apiVersion: v1
kind: Service
metadata:
  name: podinfo-ui-test
  namespace: devdeploy-workloads
  labels:
    app.kubernetes.io/name: podinfo-ui-test
    app.kubernetes.io/managed-by: devdeploy-hub
    devdeploy.io/application: podinfo-ui-test
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: podinfo-ui-test
    devdeploy.io/application: podinfo-ui-test
  ports:
    - name: http
      port: 9898
      targetPort: 9898
      protocol: TCP
